# Generated by Django 3.2 on 2023-07-03 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='Cite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.cite'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='lib_Batiment',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='nb_etage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='nb_logts',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cite',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='cite',
            name='lib_Cite',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cite',
            name='nb_logts',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cite',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.unite'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.logement'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='mois',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='occupant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.occupant'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.unite'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='charge',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_cnt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_strt_loyer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='loyer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='mnt_tva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='occupant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.occupant'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='total_of_month',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logement',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.batiment'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.contrat'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logement',
            name='prix_logement',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='logement',
            name='surface',
            field=models.FloatField(default='m2'),
        ),
        migrations.AlterField(
            model_name='logement',
            name='type_logement',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='date_naiss',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='lieu_naiss',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='nom_oc',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='oc_id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='occupant',
            name='prenom_oc',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='unite',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='unite',
            name='lib_unit',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='unite',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET, to='data.wilaya'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='lib_wilaya',
            field=models.CharField(max_length=120),
        ),
    ]
